### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by xqt** [overcat/requests-sse#11]
Pywikibot framework uses sseclient which is not maintained any longer for 3 years. Therefore I would like to change the SSE client moving from sseclient to request-sse. Unfortunately requests-sse does not support Python 3.7; would you support it for Pywikibot framework?

See also: https://phabricator.wikimedia.org/T309380

**Comment by overcat** [comment]
In version 0.3.1, I added support for 3.7. However, the lifecycle of 3.7 has already ended (see https://endoflife.date/python), and in future versions, I may have to drop the support.

**Comment by xqt** [comment]
> In version 0.3.1, I added support for 3.7. 

Great, thanks a lot

> However, the lifecycle of 3.7 has already ended (see https://endoflife.date/python), and in future versions, I may have to drop the support.

I know that but most Pywikibot users [(26 %)](https://phabricator.wikimedia.org/T350568#9382816) are having Python 3.7 possibly due to toolforge support. I guess Pywikibot does not drop Python 3.7 support before 2025. Anyway if you drop that support we would still have support for it with older releases of requests-sse.

**Comment by xqt** [comment]
@overcat: Pywikibot has dropped Python 3.7 support recently. From our scope the minimal requirement can be increased to Python 3.8. See https://phabricator.wikimedia.org/T378893.
